begin;
insert into kb_entry_versions (entry_id, title, content, edited_by) select id, title, content, updated_by from kb_entries where article_number in (6,8,14,22,23,29,30);
update kb_entries set content = replace(replace(replace(replace(replace(replace(replace(replace(content, $q$A project is **Completed** when all its work is finished, and **closed** when its WBS has been reviewed and its final numbers locked. Completed comes first; closing is the final sign-off. Click a section below to expand it.$q$, $q$Every project has one **Stage**. Finishing a project is one step: when every task is Done or Cancelled, the owner sends **Close Project** from the WBS page. While it waits the Stage is {orange:Closing}; once approved it's {success:Closed} (Completed), with Phase set to Done and the final numbers locked. Click a section below to expand it.

| Stage | What it means | How it gets there |
|---|---|---|
| {neutral:Draft} | Being planned. Tasks are private to the owner and their leaders. | New project |
| {gold:Awaiting Start} | A Start Project request is waiting for approval. | Owner sends **Start Project** (WBS page) |
| {accent:Active} | Started; the team is working on it. | Start Project approved, or Resume |
| {orange:Closing} | A Close Project request is waiting for approval. | Owner sends **Close Project** (all tasks Done or Cancelled) |
| {purple:Paused} | On hold. | **Pause** (reason required) |
| {success:Closed} | Finished. Final numbers are locked. | Close Project approved |
| {danger:Cancelled} | Stopped before it was finished. | **Cancel project** |$q$), $q$| | Project status **Completed** | WBS status **Closed** |
|---|---|---|
| What it means | All work is finished | Final numbers reviewed and locked |
| Who sets it | Project owner (manual) | Close Project request, routed to the first person up the owner's line with the Project Close right (or Full Access) |
| Tasks can be reopened | {success:Yes} — the project moves back to In Progress | {danger:No} — reopen the project through WBS first |
| Follow-up time allowed | {success:Yes} | {danger:No} |
| Existing logs can be corrected | {success:Yes} | {success:Yes} |$q$, $q$| | {accent:Active} · Ready to close | {success:Closed} |
|---|---|---|
| What it means | Every task is Done or Cancelled | Close Project approved; final numbers locked |
| Who sets it | Automatic tag | Close Project request, routed to the first person up the owner's line with the Project Close right (or Full Access) |
| Tasks can be reopened | {success:Yes} | {danger:No} — reopen the project through WBS first |
| Follow-up time allowed | {success:Yes} | {danger:No} |
| Existing logs can be corrected | {success:Yes} | {success:Yes} |$q$), $q$### Marking a project Completed
Project status is still set by hand, but Tempo checks the work first:

- A project can be set to **Completed** only when every task is **Done** or **Cancelled**.
- A project with **no tasks** can't be Completed or closed: no tasks means nothing happened. If work was done, add the tasks first; if not, **delete** the project (Tempo offers both options).
- If any task is still open, you'll see the list of open tasks (Task ID, name, status). **Finish** them, or **cancel** the ones that are no longer needed (with a reason) — then set the project to Completed.
- This matches **Actual Progress**: cancelled tasks don't count, so 100% means every remaining task is Done.
- If the whole project was stopped rather than finished, use **Cancelled** or **Paused**, not Completed.$q$, $q$### When a project is ready to close
There's no separate "mark Completed" step. Tempo checks the work for you:

- When every task is **Done** or **Cancelled**, the project shows {gold:Ready to close} next to its Stage.
- A project with **no tasks** can't be closed: no tasks means nothing happened. If work was done, add the tasks first; if not, move the project to Archive.
- If any task is still open, Close Project lists them. **Finish** them, or **cancel** the ones no longer needed (with a reason).
- If the whole project was stopped rather than finished, use **Cancel project** or **Pause** from the Stage cell, not Close Project.$q$), $q$### Reopening a task on a Completed project
If a task needs more work after the project was marked Completed, its Immediate Supervisor (or anyone above) can reopen it. Before it happens you'll see a warning, and then:

- the task goes back to **In Progress**, so Actual Progress drops below 100%;
- the project **automatically moves back to In Progress** (the phase moves to the latest In Progress phase);
- the project can only be set to Completed again once that task is Done or Cancelled.$q$, $q$### Reopening a task before closing
If a task needs more work while the project is still Active, its Immediate Supervisor (or anyone above) can reopen it. The task goes back to **In Progress**, so the {gold:Ready to close} tag goes away until it's Done or Cancelled again.$q$), $q$When a project is Completed, the owner reviews the WBS and requests closure from the WBS page.$q$, $q$When the project is Ready to close, the owner reviews the WBS and sends **Close Project** from the WBS page. Phase isn't needed: closing sets it to Done.$q$), $q$**Projects ready to close** lists Completed projects with how long ago they were completed and how many tasks still await validation, with a link to the WBS. **Completed projects have open tasks** flags any Completed project that has open work.$q$, $q$**Projects ready to close** lists your Active projects where every task is Done or Cancelled, with how long ago the last task was done and how many tasks still await validation, with a link to the WBS.$q$), $q$- **Projects & Tasks**: the WBS Status column shows a {gold:Ready to close} tag on Completed projects that aren't closed yet.$q$, $q$- **Projects & Tasks**: the Stage column shows a {gold:Ready to close} tag.$q$), $q$lists projects Completed **14+ days** ago that still aren't closed, so supervisors can follow up.$q$, $q$shows **Ready to close** (all done, no Close Project request yet) and **Closing** (request waiting), so supervisors can follow up.$q$), updated_by = 'e7e52a30-4c13-449b-889d-280dc0ca16c6', updated_at = now() where article_number = 6;
update kb_entries set content = replace(replace(replace(replace(content, $q$1. Set the project's Status to **Paused** (single project or a bulk selection).$q$, $q$1. Click the project's **Stage** and choose **Pause** (single project), or use **Stage → Pause** on a bulk selection.$q$), $q$and only an active project (not Draft, Completed, Cancelled or Closed).$q$, $q$and only an Active project (not Draft, Awaiting Start, Closed or Cancelled).$q$), $q$1. Set Status back to **In Progress**. This works immediately.$q$, $q$1. Click the project's **Stage** and choose **Resume**. It's Active again straight away.$q$), $q$A paused project moved straight to Completed or Cancelled doesn't need a schedule review (Completed still requires every task to be Done or Cancelled).$q$, $q$A paused project that's cancelled (**Cancel project**) doesn't need a schedule review.$q$), updated_by = 'e7e52a30-4c13-449b-889d-280dc0ca16c6', updated_at = now() where article_number = 8;
update kb_entries set content = replace(replace(replace(replace(replace(replace(content, $q$| **Status** | Lifecycle: {neutral:Not Started}, {accent:In Progress}, {success:Completed}, {purple:Paused}, {danger:Cancelled}. Stays Not Started while the project is in Draft. |$q$, $q$| **Stage** | The project's one lifecycle: {neutral:Draft}, {gold:Awaiting Start}, {accent:Active}, {orange:Closing}, {purple:Paused}, {success:Closed}, {danger:Cancelled}. Set by actions (Start Project, Pause/Resume, Cancel, Close Project), never typed in. Tags on Active projects: {gold:Ready to close} (every task Done or Cancelled) and {slate:Ongoing}. See [[Completing & Closing a Project]]. |$q$), $q$| **Phase** | Pipeline stage. Not Started = Backlog / Queued. In Progress = Scoping / Design / Development / Evaluation / Delivery. Completed = Done (automatic). Paused or Cancelled freeze the phase where it was. |$q$, $q$| **Phase** | Where an **Active** project is in production: Scoping, Design, Development, Evaluation, Delivery. Set to Done automatically when the project is Closed. Paused or Cancelled freeze it where it was. |$q$), $q$| **WBS Status** | Where the plan is: Draft, Awaiting Start, Start Project Declined, Baseline Locked, Changed After Baseline, Ongoing (Training Delivery and Ongoing containers), Closed. |$q$, $q$| **WBS Status** | Older field, now covered by **Stage** and hidden from ready-made views. Changes to the plan after Start are kept in the project's Audit Trail, not shown as a status. |$q$), $q$- **Completed** projects: {success:Completed on time} if$q$, $q$- **Closed** projects: {success:Completed on time} if$q$), $q$- Progress at 100% but Status not yet Completed: {success:Done on time · close pending} or {gold:Done late · close pending}.$q$, $q$- Progress at 100% but not Closed yet: {success:Done on time · close pending} or {gold:Done late · close pending}.$q$), $q$| **Start / Due** | Planned dates. Locked once the baseline is approved;$q$, $q$| **Start / Due** | Planned dates. Locked once Start Project is approved;$q$), updated_by = 'e7e52a30-4c13-449b-889d-280dc0ca16c6', updated_at = now() where article_number = 14;
update kb_entries set content = replace(replace(content, $q$### Draft plans are private until Start Project$q$, $q$### Stage at the top of the page
The badge beside the project name shows its **Stage**: Draft, Awaiting Start, Active, Closing, Paused, Closed or Cancelled. Changes to the plan after Start are recorded in the **Audit Trail**; they don't change the Stage.

### Draft plans are private until Start Project$q$), $q$**Request Project Closure** (sends a Close Project request)$q$, $q$**Request Project Closure** (sends a Close Project request; the Stage shows Closing until it's decided, then Closed)$q$), updated_by = 'e7e52a30-4c13-449b-889d-280dc0ca16c6', updated_at = now() where article_number = 22;
update kb_entries set content = replace(replace(replace(replace(replace(replace(replace(content, $q$| Sort, group and sub-group, hidden groups, counts | Filters (Status, Owner / Assigned to, My role, Project owner, Attention) |$q$, $q$| Sort, group and sub-group, hidden groups, counts | Filters (Stage or Status, Owner / Assigned to, My role, Project owner, Attention) |$q$), $q$- **Projects:** Owner, Status, **My role** (Owner / Contributor).$q$, $q$- **Projects:** Owner, **Stage**, **My role** (Owner / Contributor).$q$), $q$for example *Status: In Progress* from All Active Projects (formerly Active Project Portfolio).$q$, $q$for example *Stage: Active, Closing* from All Active Projects (older copies that said *Status: In Progress* were switched automatically).$q$), $q$| **Active Projects I Own** | Filters: My role Owner · Status In Progress | Project ID, Project, WBS Status, Status, Health,$q$, $q$| **Active Projects I Own** | Filters: My role Owner · Stage Active, Closing | Project ID, Project, Stage, Health,$q$), $q$| **My Active Projects** | Filters: My role Owner + Contributor · Status In Progress | Project ID, Project, Owner, WBS Status, Health,$q$, $q$| **My Active Projects** | Filters: My role Owner + Contributor · Stage Active, Closing | Project ID, Project, Owner, Stage, Health,$q$), $q$| **All My Projects** | Same, any status | As above, plus Status | Same |$q$, $q$| **All My Projects** | Same, any Stage | As above | Same |$q$), $q$The Projects board can be grouped by Phase (default), Status, **Health**, WBS Status,$q$, $q$The Projects board can be grouped by Phase (default), **Stage**, **Health**,$q$), updated_by = 'e7e52a30-4c13-449b-889d-280dc0ca16c6', updated_at = now() where article_number = 23;
update kb_entries set content = replace(replace(replace(content, $q$| **Everyone else** | See the project row only, marked Draft | As usual |$q$, $q$| **Everyone else** | See the project row only, Stage Draft | As usual |$q$), $q$"Draft" includes projects waiting for Start Project approval.$q$, $q$Draft also covers **Awaiting Start** (a Start Project request is waiting for approval).$q$), $q$**Start Project** is the one switch from planning to commitment. Once it's approved:$q$, $q$**Start Project** is the one switch from planning to commitment. Once it's approved the Stage moves from Draft to **Active**, and:$q$), updated_by = 'e7e52a30-4c13-449b-889d-280dc0ca16c6', updated_at = now() where article_number = 29;
update kb_entries set content = replace(replace(content, $q$## Projects & Tasks

$q$, $q$## Projects & Tasks

### One Stage for every project
Status, WBS Status and Phase used to tell overlapping stories. Every project now has **one Stage**: {neutral:Draft} → {gold:Awaiting Start} → {accent:Active} → {orange:Closing} → {success:Closed}, plus {purple:Paused} and {danger:Cancelled}. Stage isn't typed in; it moves when you **Start Project**, **Pause / Resume**, **Cancel**, or **Close Project**. There's no separate "mark Completed" step any more: approving **Close Project** sets the project to Closed. Active projects show a **Ready to close** tag when every task is Done or Cancelled, and **Ongoing** for Training Delivery and Ongoing containers. Phase (Scoping, Design, Development, Evaluation, Delivery) stays as the detail inside Active.
**Related articles:** [[Completing & Closing a Project]] · [[Projects: Terms & Columns]]

$q$), $q$and the first agreed dates are now kept as **Committed** dates$q$, $q$every project has one **Stage**, and the first agreed dates are now kept as **Committed** dates$q$), updated_by = 'e7e52a30-4c13-449b-889d-280dc0ca16c6', updated_at = now() where article_number = 30;
commit;
select article_number, length(content) from kb_entries where article_number in (6,8,14,22,23,29,30) order by 1;